name: ${pom.name}
version: ${pom.version}
authors: [MrCubee, Redwoub, jeffcheasey88]
api-version: 1.8.8
website: https://github.com/ArkadGamesNetwork/SurvivalGames-Kit
main: fr.mrcubee.survivalgames.kit.SurvivalGamesKit
depend: [SurvivalGames]